### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by DJinsis** [reppy4620/PainTorch#2]
Hello, what data set is the data set for your training? I didn't get the result you said. could you tell me？

**Comment by reppy4620** [comment]
hi, @DJinsis.
Dataset I use are about 10,000 high quality images in Pinterest.
i searched in Pinterest e.g."girl illustration" and click image you think good.
Then scroll down, you can find a lot of related high quality images.
To collect them, i use this [xjdeng/pinterest-image-scraper](https://github.com/xjdeng/pinterest-image-scraper)(i use this repo with no special reason)
Note that you want to make good result, use colorful image not black-and-white images.
sorry for not good english.
